export const SOCIAL_PLATFORMS = [
    "Personal Website",
    "LinkedIn",
    "GitHub",
    "Instagram",
    "X (Twitter)",
    "Facebook",
    "TikTok",
    "Threads",
    "YouTube",
    "Twitch",
    "Reddit",
    "Telegram",
    "Medium",
    "Substack",
    "Behance",
    "Dribbble",
    "SoundCloud",
    "Spotify",
] 